#!/usr/bin/bash
sudo apt update;
sudo apt upgrade;
sudo apt install openjdk-17-jre-headless;
sudo apt install screen;
mkdir mcserver;
cd mcserver;
wget https://piston-data.mojang.com/v1/objects/c9df48efed58511cdd0213c56b9013a7b5c9ac1f/server.jar;
